apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app2-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app2-config
        configMap:
          name: app2-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>App 2</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; background-color: #e6ffe6; }
        h1 { color: #2e8b57; }
      </style>
    </head>
    <body>
      <h1>Welcome to App 2</h1>
      <p>This is the second application running on K3s with 3 replicas.</p>
      <p>Pod Name: ju</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
  - port: 80
    targetPort: 80
