apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app3-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app3-config
        configMap:
          name: app3-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>App 3 (Default)</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; background-color: #ffe6e6; }
        h1 { color: #b22222; }
      </style>
    </head>
    <body>
      <h1>Welcome to App 3 (Default)</h1>
      <p>This is the default application running on K3s.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  selector:
    app: app3
  ports:
  - port: 80
    targetPort: 80
