Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    config.vm.define "jmastoraS" do |server|
      server.vm.hostname = "jmastoraS"
      server.vm.network "private_network", ip: "192.168.56.110"
      
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
        vb.name = "jmastoraS-p2"
      end

      server.vm.provision "shell", path: "scripts/install_k3s.sh"
    end
  end